[package]
name = "compact-indexer"
version = "0.0.1"
authors = ["Eugene The Dream"]
edition = "2018"

[dependencies]
actix = "=0.13.0"
actix-web = "4.3.0"
# actix-http = "=3.0.0-beta.6"
actix-tls = "3.0.0"
actix-rt = "2.2.0"
bigdecimal = "=0.1.0"
anyhow = "1.0.51"

openssl-probe = { version = "0.1.2" }
# futures = "0.3.5"
tokio = { version = "1.1", features = ["time", "sync", "rt-multi-thread"] }
tokio-stream = { version = "0.1" }
dotenv = "0.15.0"
tracing = "0.1.13"
tracing-subscriber = "0.2.4"

serde = { version = "1", features = [ "derive" ] }
serde_json = "1"

near-indexer = { git = "https://github.com/near/nearcore", rev = "1.35.0" }

clickhouse-rs = { git = "https://github.com/evgenykuzyakov/clickhouse-rs", rev = "c22d2b1ec04c70d40a35ab3c4dfa1c87d862a0e6", features = ['tokio_io', 'tls'] }
